set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_p[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {master_slave_n[11]}]


set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[0]}]
### VFAT2

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[12]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[13]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[14]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[15]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[1]}]
### VFAT3

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[16]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[17]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[17]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[18]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[18]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[19]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[19]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[20]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[20]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[21]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[21]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[22]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[22]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[23]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[23]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[2]}]
### VFAT4

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[24]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[24]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[25]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[25]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[26]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[26]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[27]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[27]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[28]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[28]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[29]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[29]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[30]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[30]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[31]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[31]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[3]}]
### VFAT5

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[32]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[32]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[33]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[33]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[34]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[34]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[35]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[35]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[36]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[36]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[37]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[37]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[38]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[38]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[39]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[39]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[4]}]
### VFAT6

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[40]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[40]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[41]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[41]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[42]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[42]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[43]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[43]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[44]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[44]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[45]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[45]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[46]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[46]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[47]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[47]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[5]}]
### VFAT7

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[48]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[48]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[49]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[49]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[50]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[50]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[51]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[51]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[52]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[52]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[53]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[53]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[54]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[54]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[55]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[55]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[6]}]
### VFAT8

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[56]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[56]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[57]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[57]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[58]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[58]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[59]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[59]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[60]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[60]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[61]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[61]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[62]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[62]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[63]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[63]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[7]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[7]}]
### VFAT9

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[64]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[64]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[65]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[65]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[66]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[66]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[67]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[67]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[68]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[68]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[69]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[69]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[70]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[70]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[71]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[71]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[8]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[8]}]
### VFAT10

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[72]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[72]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[73]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[73]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[74]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[74]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[75]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[75]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[76]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[76]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[77]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[77]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[78]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[78]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[79]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[79]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[9]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[9]}]
### VFAT11

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[80]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[80]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[81]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[81]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[82]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[82]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[83]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[83]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[84]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[84]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[85]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[85]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[86]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[86]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[87]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[87]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[10]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[10]}]
### VFAT12

set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[88]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[88]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[89]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[89]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[90]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[90]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[91]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[91]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[92]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[92]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[93]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[93]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[94]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[94]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_p[95]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sbits_n[95]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_p[11]}]
set_property IOSTANDARD LVDS_25 [get_ports {vfat_sot_n[11]}]

set_property IOSTANDARD LVDS_25 [get_ports logic_clock_p]
set_property IOSTANDARD LVDS_25 [get_ports logic_clock_n]

set_property IOSTANDARD LVDS_25 [get_ports elink_clock_p]
set_property IOSTANDARD LVDS_25 [get_ports elink_clock_n]

set_property IOSTANDARD LVDS_25 [get_ports elink_i_p]
set_property IOSTANDARD LVDS_25 [get_ports elink_i_n]
set_property IOSTANDARD LVDS_25 [get_ports elink_o_p]
set_property IOSTANDARD LVDS_25 [get_ports elink_o_n]


set_property IOSTANDARD LVCMOS25 [get_ports {vtrx_mabs_i[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {vtrx_mabs_i[1]}]

#set_property    IOSTANDARD    LVDS_25    [get_ports TP8]
#set_property    IOSTANDARD    LVDS_25    [get_ports TP9]
#set_property    IOSTANDARD    LVDS_25    [get_ports TP10]
#set_property    IOSTANDARD    LVDS_25    [get_ports TP11]

set_property IOSTANDARD LVCMOS25 [get_ports {led_o[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports master_slave]
set_property IOSTANDARD LVCMOS25 [get_ports {gbt_rxready_i[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gbt_rxready_i[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gbt_rxvalid_i[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gbt_rxvalid_i[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gbt_txready_i[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gbt_txready_i[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gbt_txvalid_o[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {gbt_txvalid_o[0]}]






