tables:
	bash fix_tables.sh address_table_ge21.org address_table_ge11-long.org address_table_ge11-short.org

latex:
	pdflatex address_table_ge21.tex
	pdflatex address_table_ge11-long.tex
	pdflatex address_table_ge11-short.tex
