-------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version : 3.6
--  \   \         Application : 7 Series FPGAs Transceivers Wizard
--  /   /         Filename : gtp.vhd
-- /___/   /\
-- \   \  /  \
--  \___\/\___\
--
--
-- Module gtp (a Core Top)
-- Generated by Xilinx 7 Series FPGAs Transceivers Wizard
--
--
-- (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
--
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
--
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
--
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
--
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.


library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
library UNISIM;
use UNISIM.VCOMPONENTS.all;


--***************************** Entity Declaration ****************************
entity gtp is
  port
    (
      SYSCLK_IN                   : in  std_logic;
      SOFT_RESET_TX_IN            : in  std_logic;
      DONT_RESET_ON_DATA_ERROR_IN : in  std_logic;
      GT0_TX_FSM_RESET_DONE_OUT   : out std_logic;
      GT0_RX_FSM_RESET_DONE_OUT   : out std_logic;
      GT0_DATA_VALID_IN           : in  std_logic;
      GT0_TX_MMCM_LOCK_IN         : in  std_logic;
      GT0_TX_MMCM_RESET_OUT       : out std_logic;
      GT1_TX_FSM_RESET_DONE_OUT   : out std_logic;
      GT1_RX_FSM_RESET_DONE_OUT   : out std_logic;
      GT1_DATA_VALID_IN           : in  std_logic;
      GT1_TX_MMCM_LOCK_IN         : in  std_logic;
      GT1_TX_MMCM_RESET_OUT       : out std_logic;
      GT2_TX_FSM_RESET_DONE_OUT   : out std_logic;
      GT2_RX_FSM_RESET_DONE_OUT   : out std_logic;
      GT2_DATA_VALID_IN           : in  std_logic;
      GT2_TX_MMCM_LOCK_IN         : in  std_logic;
      GT2_TX_MMCM_RESET_OUT       : out std_logic;
      GT3_TX_FSM_RESET_DONE_OUT   : out std_logic;
      GT3_RX_FSM_RESET_DONE_OUT   : out std_logic;
      GT3_DATA_VALID_IN           : in  std_logic;
      GT3_TX_MMCM_LOCK_IN         : in  std_logic;
      GT3_TX_MMCM_RESET_OUT       : out std_logic;

      --_________________________________________________________________________
      --GT0  (X0Y0)
      --____________________________CHANNEL PORTS________________________________
      ---------------------------- Channel - DRP Ports  --------------------------
      gt0_drpaddr_in           : in  std_logic_vector(8 downto 0);
      gt0_drpclk_in            : in  std_logic;
      gt0_drpdi_in             : in  std_logic_vector(15 downto 0);
      gt0_drpdo_out            : out std_logic_vector(15 downto 0);
      gt0_drpen_in             : in  std_logic;
      gt0_drprdy_out           : out std_logic;
      gt0_drpwe_in             : in  std_logic;
      ------------------------------- Loopback Ports -----------------------------
      gt0_loopback_in          : in  std_logic_vector(2 downto 0);
      --------------------- RX Initialization and Reset Ports --------------------
      gt0_eyescanreset_in      : in  std_logic;
      -------------------------- RX Margin Analysis Ports ------------------------
      gt0_eyescandataerror_out : out std_logic;
      gt0_eyescantrigger_in    : in  std_logic;
      ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
      gt0_dmonitorout_out      : out std_logic_vector(14 downto 0);
      ------------- Receive Ports - RX Initialization and Reset Ports ------------
      gt0_gtrxreset_in         : in  std_logic;
      gt0_rxlpmreset_in        : in  std_logic;
      --------------------- TX Initialization and Reset Ports --------------------
      gt0_gttxreset_in         : in  std_logic;
      gt0_txuserrdy_in         : in  std_logic;
      ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
      gt0_txdata_in            : in  std_logic_vector(15 downto 0);
      gt0_txusrclk_in          : in  std_logic;
      gt0_txusrclk2_in         : in  std_logic;
      ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
      gt0_txcharisk_in         : in  std_logic_vector(1 downto 0);
      --------------- Transmit Ports - TX Configurable Driver Ports --------------
      gt0_gtptxn_out           : out std_logic;
      gt0_gtptxp_out           : out std_logic;
      gt0_txdiffctrl_in        : in  std_logic_vector(3 downto 0);
      ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
      gt0_txoutclk_out         : out std_logic;
      gt0_txoutclkfabric_out   : out std_logic;
      gt0_txoutclkpcs_out      : out std_logic;
      ------------- Transmit Ports - TX Initialization and Reset Ports -----------
      gt0_txpcsreset_in        : in  std_logic;
      gt0_txpmareset_in        : in  std_logic;
      gt0_txresetdone_out      : out std_logic;

      --GT1  (X0Y1)
      --____________________________CHANNEL PORTS________________________________
      ---------------------------- Channel - DRP Ports  --------------------------
      gt1_drpaddr_in           : in  std_logic_vector(8 downto 0);
      gt1_drpclk_in            : in  std_logic;
      gt1_drpdi_in             : in  std_logic_vector(15 downto 0);
      gt1_drpdo_out            : out std_logic_vector(15 downto 0);
      gt1_drpen_in             : in  std_logic;
      gt1_drprdy_out           : out std_logic;
      gt1_drpwe_in             : in  std_logic;
      ------------------------------- Loopback Ports -----------------------------
      gt1_loopback_in          : in  std_logic_vector(2 downto 0);
      --------------------- RX Initialization and Reset Ports --------------------
      gt1_eyescanreset_in      : in  std_logic;
      -------------------------- RX Margin Analysis Ports ------------------------
      gt1_eyescandataerror_out : out std_logic;
      gt1_eyescantrigger_in    : in  std_logic;
      ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
      gt1_dmonitorout_out      : out std_logic_vector(14 downto 0);
      ------------- Receive Ports - RX Initialization and Reset Ports ------------
      gt1_gtrxreset_in         : in  std_logic;
      gt1_rxlpmreset_in        : in  std_logic;
      --------------------- TX Initialization and Reset Ports --------------------
      gt1_gttxreset_in         : in  std_logic;
      gt1_txuserrdy_in         : in  std_logic;
      ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
      gt1_txdata_in            : in  std_logic_vector(15 downto 0);
      gt1_txusrclk_in          : in  std_logic;
      gt1_txusrclk2_in         : in  std_logic;
      ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
      gt1_txcharisk_in         : in  std_logic_vector(1 downto 0);
      --------------- Transmit Ports - TX Configurable Driver Ports --------------
      gt1_gtptxn_out           : out std_logic;
      gt1_gtptxp_out           : out std_logic;
      gt1_txdiffctrl_in        : in  std_logic_vector(3 downto 0);
      ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
      gt1_txoutclk_out         : out std_logic;
      gt1_txoutclkfabric_out   : out std_logic;
      gt1_txoutclkpcs_out      : out std_logic;
      ------------- Transmit Ports - TX Initialization and Reset Ports -----------
      gt1_txpcsreset_in        : in  std_logic;
      gt1_txpmareset_in        : in  std_logic;
      gt1_txresetdone_out      : out std_logic;

      --GT2  (X0Y2)
      --____________________________CHANNEL PORTS________________________________
      ---------------------------- Channel - DRP Ports  --------------------------
      gt2_drpaddr_in           : in  std_logic_vector(8 downto 0);
      gt2_drpclk_in            : in  std_logic;
      gt2_drpdi_in             : in  std_logic_vector(15 downto 0);
      gt2_drpdo_out            : out std_logic_vector(15 downto 0);
      gt2_drpen_in             : in  std_logic;
      gt2_drprdy_out           : out std_logic;
      gt2_drpwe_in             : in  std_logic;
      ------------------------------- Loopback Ports -----------------------------
      gt2_loopback_in          : in  std_logic_vector(2 downto 0);
      --------------------- RX Initialization and Reset Ports --------------------
      gt2_eyescanreset_in      : in  std_logic;
      -------------------------- RX Margin Analysis Ports ------------------------
      gt2_eyescandataerror_out : out std_logic;
      gt2_eyescantrigger_in    : in  std_logic;
      ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
      gt2_dmonitorout_out      : out std_logic_vector(14 downto 0);
      ------------- Receive Ports - RX Initialization and Reset Ports ------------
      gt2_gtrxreset_in         : in  std_logic;
      gt2_rxlpmreset_in        : in  std_logic;
      --------------------- TX Initialization and Reset Ports --------------------
      gt2_gttxreset_in         : in  std_logic;
      gt2_txuserrdy_in         : in  std_logic;
      ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
      gt2_txdata_in            : in  std_logic_vector(15 downto 0);
      gt2_txusrclk_in          : in  std_logic;
      gt2_txusrclk2_in         : in  std_logic;
      ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
      gt2_txcharisk_in         : in  std_logic_vector(1 downto 0);
      --------------- Transmit Ports - TX Configurable Driver Ports --------------
      gt2_gtptxn_out           : out std_logic;
      gt2_gtptxp_out           : out std_logic;
      gt2_txdiffctrl_in        : in  std_logic_vector(3 downto 0);
      ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
      gt2_txoutclk_out         : out std_logic;
      gt2_txoutclkfabric_out   : out std_logic;
      gt2_txoutclkpcs_out      : out std_logic;
      ------------- Transmit Ports - TX Initialization and Reset Ports -----------
      gt2_txpcsreset_in        : in  std_logic;
      gt2_txpmareset_in        : in  std_logic;
      gt2_txresetdone_out      : out std_logic;

      --GT3  (X0Y3)
      --____________________________CHANNEL PORTS________________________________
      ---------------------------- Channel - DRP Ports  --------------------------
      gt3_drpaddr_in           : in  std_logic_vector(8 downto 0);
      gt3_drpclk_in            : in  std_logic;
      gt3_drpdi_in             : in  std_logic_vector(15 downto 0);
      gt3_drpdo_out            : out std_logic_vector(15 downto 0);
      gt3_drpen_in             : in  std_logic;
      gt3_drprdy_out           : out std_logic;
      gt3_drpwe_in             : in  std_logic;
      ------------------------------- Loopback Ports -----------------------------
      gt3_loopback_in          : in  std_logic_vector(2 downto 0);
      --------------------- RX Initialization and Reset Ports --------------------
      gt3_eyescanreset_in      : in  std_logic;
      -------------------------- RX Margin Analysis Ports ------------------------
      gt3_eyescandataerror_out : out std_logic;
      gt3_eyescantrigger_in    : in  std_logic;
      ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
      gt3_dmonitorout_out      : out std_logic_vector(14 downto 0);
      ------------- Receive Ports - RX Initialization and Reset Ports ------------
      gt3_gtrxreset_in         : in  std_logic;
      gt3_rxlpmreset_in        : in  std_logic;
      --------------------- TX Initialization and Reset Ports --------------------
      gt3_gttxreset_in         : in  std_logic;
      gt3_txuserrdy_in         : in  std_logic;
      ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
      gt3_txdata_in            : in  std_logic_vector(15 downto 0);
      gt3_txusrclk_in          : in  std_logic;
      gt3_txusrclk2_in         : in  std_logic;
      ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
      gt3_txcharisk_in         : in  std_logic_vector(1 downto 0);
      --------------- Transmit Ports - TX Configurable Driver Ports --------------
      gt3_gtptxn_out           : out std_logic;
      gt3_gtptxp_out           : out std_logic;
      gt3_txdiffctrl_in        : in  std_logic_vector(3 downto 0);
      ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
      gt3_txoutclk_out         : out std_logic;
      gt3_txoutclkfabric_out   : out std_logic;
      gt3_txoutclkpcs_out      : out std_logic;
      ------------- Transmit Ports - TX Initialization and Reset Ports -----------
      gt3_txpcsreset_in        : in  std_logic;
      gt3_txpmareset_in        : in  std_logic;
      gt3_txresetdone_out      : out std_logic;


      --____________________________COMMON PORTS________________________________
      GT0_PLL0OUTCLK_IN     : in  std_logic;
      GT0_PLL0OUTREFCLK_IN  : in  std_logic;
      GT0_PLL0RESET_OUT     : out std_logic;
      GT0_PLL0LOCK_IN       : in  std_logic;
      GT0_PLL0REFCLKLOST_IN : in  std_logic;
      GT0_PLL1OUTCLK_IN     : in  std_logic;
      GT0_PLL1OUTREFCLK_IN  : in  std_logic

      );
end gtp;

architecture RTL of gtp is
  attribute DowngradeIPIdentifiedWarnings        : string;
  attribute DowngradeIPIdentifiedWarnings of RTL : architecture is "yes";

  attribute X_CORE_INFO                 : string;
  attribute X_CORE_INFO of RTL          : architecture is "gtp,gtwizard_v3_6_11,{protocol_file=Start_from_scratch}";
  attribute CORE_GENERATION_INFO        : string;
  attribute CORE_GENERATION_INFO of RTL : architecture is "gtp,gtwizard_v3_6_11,{protocol_file=Start_from_scratch}";

--**************************Component Declarations*****************************

  component gtp_init
    generic
      (
        EXAMPLE_SIM_GTRESET_SPEEDUP : string  := "TRUE";  -- simulation setting for GT SecureIP model
        EXAMPLE_SIMULATION          : integer := 0;       -- Set to 1 for simulation

        STABLE_CLOCK_PERIOD   : integer := 25;
        -- Set to 1 for simulation
        EXAMPLE_USE_CHIPSCOPE : integer := 0  -- Set to 1 to use Chipscope to drive resets

        );
    port
      (
        SYSCLK_IN                   : in  std_logic;
        SOFT_RESET_TX_IN            : in  std_logic;
        DONT_RESET_ON_DATA_ERROR_IN : in  std_logic;
        GT0_TX_FSM_RESET_DONE_OUT   : out std_logic;
        GT0_RX_FSM_RESET_DONE_OUT   : out std_logic;
        GT0_DATA_VALID_IN           : in  std_logic;
        GT0_TX_MMCM_LOCK_IN         : in  std_logic;
        GT0_TX_MMCM_RESET_OUT       : out std_logic;
        GT1_TX_FSM_RESET_DONE_OUT   : out std_logic;
        GT1_RX_FSM_RESET_DONE_OUT   : out std_logic;
        GT1_DATA_VALID_IN           : in  std_logic;
        GT1_TX_MMCM_LOCK_IN         : in  std_logic;
        GT1_TX_MMCM_RESET_OUT       : out std_logic;
        GT2_TX_FSM_RESET_DONE_OUT   : out std_logic;
        GT2_RX_FSM_RESET_DONE_OUT   : out std_logic;
        GT2_DATA_VALID_IN           : in  std_logic;
        GT2_TX_MMCM_LOCK_IN         : in  std_logic;
        GT2_TX_MMCM_RESET_OUT       : out std_logic;
        GT3_TX_FSM_RESET_DONE_OUT   : out std_logic;
        GT3_RX_FSM_RESET_DONE_OUT   : out std_logic;
        GT3_DATA_VALID_IN           : in  std_logic;
        GT3_TX_MMCM_LOCK_IN         : in  std_logic;
        GT3_TX_MMCM_RESET_OUT       : out std_logic;

        --_________________________________________________________________________
        --GT0  (X0Y0)
        --____________________________CHANNEL PORTS________________________________
        ---------------------------- Channel - DRP Ports  --------------------------
        gt0_drpaddr_in           : in  std_logic_vector(8 downto 0);
        gt0_drpclk_in            : in  std_logic;
        gt0_drpdi_in             : in  std_logic_vector(15 downto 0);
        gt0_drpdo_out            : out std_logic_vector(15 downto 0);
        gt0_drpen_in             : in  std_logic;
        gt0_drprdy_out           : out std_logic;
        gt0_drpwe_in             : in  std_logic;
        ------------------------------- Loopback Ports -----------------------------
        gt0_loopback_in          : in  std_logic_vector(2 downto 0);
        --------------------- RX Initialization and Reset Ports --------------------
        gt0_eyescanreset_in      : in  std_logic;
        -------------------------- RX Margin Analysis Ports ------------------------
        gt0_eyescandataerror_out : out std_logic;
        gt0_eyescantrigger_in    : in  std_logic;
        ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
        gt0_dmonitorout_out      : out std_logic_vector(14 downto 0);
        ------------- Receive Ports - RX Initialization and Reset Ports ------------
        gt0_gtrxreset_in         : in  std_logic;
        gt0_rxlpmreset_in        : in  std_logic;
        --------------------- TX Initialization and Reset Ports --------------------
        gt0_gttxreset_in         : in  std_logic;
        gt0_txuserrdy_in         : in  std_logic;
        ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
        gt0_txdata_in            : in  std_logic_vector(15 downto 0);
        gt0_txusrclk_in          : in  std_logic;
        gt0_txusrclk2_in         : in  std_logic;
        ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
        gt0_txcharisk_in         : in  std_logic_vector(1 downto 0);
        --------------- Transmit Ports - TX Configurable Driver Ports --------------
        gt0_gtptxn_out           : out std_logic;
        gt0_gtptxp_out           : out std_logic;
        gt0_txdiffctrl_in        : in  std_logic_vector(3 downto 0);
        ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        gt0_txoutclk_out         : out std_logic;
        gt0_txoutclkfabric_out   : out std_logic;
        gt0_txoutclkpcs_out      : out std_logic;
        ------------- Transmit Ports - TX Initialization and Reset Ports -----------
        gt0_txpcsreset_in        : in  std_logic;
        gt0_txpmareset_in        : in  std_logic;
        gt0_txresetdone_out      : out std_logic;

        --GT1  (X0Y1)
        --____________________________CHANNEL PORTS________________________________
        ---------------------------- Channel - DRP Ports  --------------------------
        gt1_drpaddr_in           : in  std_logic_vector(8 downto 0);
        gt1_drpclk_in            : in  std_logic;
        gt1_drpdi_in             : in  std_logic_vector(15 downto 0);
        gt1_drpdo_out            : out std_logic_vector(15 downto 0);
        gt1_drpen_in             : in  std_logic;
        gt1_drprdy_out           : out std_logic;
        gt1_drpwe_in             : in  std_logic;
        ------------------------------- Loopback Ports -----------------------------
        gt1_loopback_in          : in  std_logic_vector(2 downto 0);
        --------------------- RX Initialization and Reset Ports --------------------
        gt1_eyescanreset_in      : in  std_logic;
        -------------------------- RX Margin Analysis Ports ------------------------
        gt1_eyescandataerror_out : out std_logic;
        gt1_eyescantrigger_in    : in  std_logic;
        ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
        gt1_dmonitorout_out      : out std_logic_vector(14 downto 0);
        ------------- Receive Ports - RX Initialization and Reset Ports ------------
        gt1_gtrxreset_in         : in  std_logic;
        gt1_rxlpmreset_in        : in  std_logic;
        --------------------- TX Initialization and Reset Ports --------------------
        gt1_gttxreset_in         : in  std_logic;
        gt1_txuserrdy_in         : in  std_logic;
        ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
        gt1_txdata_in            : in  std_logic_vector(15 downto 0);
        gt1_txusrclk_in          : in  std_logic;
        gt1_txusrclk2_in         : in  std_logic;
        ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
        gt1_txcharisk_in         : in  std_logic_vector(1 downto 0);
        --------------- Transmit Ports - TX Configurable Driver Ports --------------
        gt1_gtptxn_out           : out std_logic;
        gt1_gtptxp_out           : out std_logic;
        gt1_txdiffctrl_in        : in  std_logic_vector(3 downto 0);
        ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        gt1_txoutclk_out         : out std_logic;
        gt1_txoutclkfabric_out   : out std_logic;
        gt1_txoutclkpcs_out      : out std_logic;
        ------------- Transmit Ports - TX Initialization and Reset Ports -----------
        gt1_txpcsreset_in        : in  std_logic;
        gt1_txpmareset_in        : in  std_logic;
        gt1_txresetdone_out      : out std_logic;

        --GT2  (X0Y2)
        --____________________________CHANNEL PORTS________________________________
        ---------------------------- Channel - DRP Ports  --------------------------
        gt2_drpaddr_in           : in  std_logic_vector(8 downto 0);
        gt2_drpclk_in            : in  std_logic;
        gt2_drpdi_in             : in  std_logic_vector(15 downto 0);
        gt2_drpdo_out            : out std_logic_vector(15 downto 0);
        gt2_drpen_in             : in  std_logic;
        gt2_drprdy_out           : out std_logic;
        gt2_drpwe_in             : in  std_logic;
        ------------------------------- Loopback Ports -----------------------------
        gt2_loopback_in          : in  std_logic_vector(2 downto 0);
        --------------------- RX Initialization and Reset Ports --------------------
        gt2_eyescanreset_in      : in  std_logic;
        -------------------------- RX Margin Analysis Ports ------------------------
        gt2_eyescandataerror_out : out std_logic;
        gt2_eyescantrigger_in    : in  std_logic;
        ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
        gt2_dmonitorout_out      : out std_logic_vector(14 downto 0);
        ------------- Receive Ports - RX Initialization and Reset Ports ------------
        gt2_gtrxreset_in         : in  std_logic;
        gt2_rxlpmreset_in        : in  std_logic;
        --------------------- TX Initialization and Reset Ports --------------------
        gt2_gttxreset_in         : in  std_logic;
        gt2_txuserrdy_in         : in  std_logic;
        ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
        gt2_txdata_in            : in  std_logic_vector(15 downto 0);
        gt2_txusrclk_in          : in  std_logic;
        gt2_txusrclk2_in         : in  std_logic;
        ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
        gt2_txcharisk_in         : in  std_logic_vector(1 downto 0);
        --------------- Transmit Ports - TX Configurable Driver Ports --------------
        gt2_gtptxn_out           : out std_logic;
        gt2_gtptxp_out           : out std_logic;
        gt2_txdiffctrl_in        : in  std_logic_vector(3 downto 0);
        ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        gt2_txoutclk_out         : out std_logic;
        gt2_txoutclkfabric_out   : out std_logic;
        gt2_txoutclkpcs_out      : out std_logic;
        ------------- Transmit Ports - TX Initialization and Reset Ports -----------
        gt2_txpcsreset_in        : in  std_logic;
        gt2_txpmareset_in        : in  std_logic;
        gt2_txresetdone_out      : out std_logic;

        --GT3  (X0Y3)
        --____________________________CHANNEL PORTS________________________________
        ---------------------------- Channel - DRP Ports  --------------------------
        gt3_drpaddr_in           : in  std_logic_vector(8 downto 0);
        gt3_drpclk_in            : in  std_logic;
        gt3_drpdi_in             : in  std_logic_vector(15 downto 0);
        gt3_drpdo_out            : out std_logic_vector(15 downto 0);
        gt3_drpen_in             : in  std_logic;
        gt3_drprdy_out           : out std_logic;
        gt3_drpwe_in             : in  std_logic;
        ------------------------------- Loopback Ports -----------------------------
        gt3_loopback_in          : in  std_logic_vector(2 downto 0);
        --------------------- RX Initialization and Reset Ports --------------------
        gt3_eyescanreset_in      : in  std_logic;
        -------------------------- RX Margin Analysis Ports ------------------------
        gt3_eyescandataerror_out : out std_logic;
        gt3_eyescantrigger_in    : in  std_logic;
        ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
        gt3_dmonitorout_out      : out std_logic_vector(14 downto 0);
        ------------- Receive Ports - RX Initialization and Reset Ports ------------
        gt3_gtrxreset_in         : in  std_logic;
        gt3_rxlpmreset_in        : in  std_logic;
        --------------------- TX Initialization and Reset Ports --------------------
        gt3_gttxreset_in         : in  std_logic;
        gt3_txuserrdy_in         : in  std_logic;
        ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
        gt3_txdata_in            : in  std_logic_vector(15 downto 0);
        gt3_txusrclk_in          : in  std_logic;
        gt3_txusrclk2_in         : in  std_logic;
        ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
        gt3_txcharisk_in         : in  std_logic_vector(1 downto 0);
        --------------- Transmit Ports - TX Configurable Driver Ports --------------
        gt3_gtptxn_out           : out std_logic;
        gt3_gtptxp_out           : out std_logic;
        gt3_txdiffctrl_in        : in  std_logic_vector(3 downto 0);
        ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
        gt3_txoutclk_out         : out std_logic;
        gt3_txoutclkfabric_out   : out std_logic;
        gt3_txoutclkpcs_out      : out std_logic;
        ------------- Transmit Ports - TX Initialization and Reset Ports -----------
        gt3_txpcsreset_in        : in  std_logic;
        gt3_txpmareset_in        : in  std_logic;
        gt3_txresetdone_out      : out std_logic;


        --____________________________COMMON PORTS________________________________
        GT0_PLL0OUTCLK_IN     : in  std_logic;
        GT0_PLL0OUTREFCLK_IN  : in  std_logic;
        GT0_PLL0RESET_OUT     : out std_logic;
        GT0_PLL0LOCK_IN       : in  std_logic;
        GT0_PLL0REFCLKLOST_IN : in  std_logic;
        GT0_PLL1OUTCLK_IN     : in  std_logic;
        GT0_PLL1OUTREFCLK_IN  : in  std_logic

        );
  end component;

--**************************** Main Body of Code *******************************
begin
  U0 : gtp_init
    generic map
    (
      EXAMPLE_SIM_GTRESET_SPEEDUP => "TRUE",
      EXAMPLE_SIMULATION          => 0,


      STABLE_CLOCK_PERIOD   => 25,
      EXAMPLE_USE_CHIPSCOPE => 0
      )
    port map
    (
      SYSCLK_IN                   => SYSCLK_IN,
      SOFT_RESET_TX_IN            => SOFT_RESET_TX_IN,
      DONT_RESET_ON_DATA_ERROR_IN => DONT_RESET_ON_DATA_ERROR_IN,
      GT0_TX_FSM_RESET_DONE_OUT   => GT0_TX_FSM_RESET_DONE_OUT,
      GT0_RX_FSM_RESET_DONE_OUT   => GT0_RX_FSM_RESET_DONE_OUT,
      GT0_DATA_VALID_IN           => GT0_DATA_VALID_IN,
      GT0_TX_MMCM_LOCK_IN         => GT0_TX_MMCM_LOCK_IN,
      GT0_TX_MMCM_RESET_OUT       => GT0_TX_MMCM_RESET_OUT,
      GT1_TX_FSM_RESET_DONE_OUT   => GT1_TX_FSM_RESET_DONE_OUT,
      GT1_RX_FSM_RESET_DONE_OUT   => GT1_RX_FSM_RESET_DONE_OUT,
      GT1_DATA_VALID_IN           => GT1_DATA_VALID_IN,
      GT1_TX_MMCM_LOCK_IN         => GT1_TX_MMCM_LOCK_IN,
      GT1_TX_MMCM_RESET_OUT       => GT1_TX_MMCM_RESET_OUT,
      GT2_TX_FSM_RESET_DONE_OUT   => GT2_TX_FSM_RESET_DONE_OUT,
      GT2_RX_FSM_RESET_DONE_OUT   => GT2_RX_FSM_RESET_DONE_OUT,
      GT2_DATA_VALID_IN           => GT2_DATA_VALID_IN,
      GT2_TX_MMCM_LOCK_IN         => GT2_TX_MMCM_LOCK_IN,
      GT2_TX_MMCM_RESET_OUT       => GT2_TX_MMCM_RESET_OUT,
      GT3_TX_FSM_RESET_DONE_OUT   => GT3_TX_FSM_RESET_DONE_OUT,
      GT3_RX_FSM_RESET_DONE_OUT   => GT3_RX_FSM_RESET_DONE_OUT,
      GT3_DATA_VALID_IN           => GT3_DATA_VALID_IN,
      GT3_TX_MMCM_LOCK_IN         => GT3_TX_MMCM_LOCK_IN,
      GT3_TX_MMCM_RESET_OUT       => GT3_TX_MMCM_RESET_OUT,

      --_________________________________________________________________________
      --GT0  (X0Y0)
      --____________________________CHANNEL PORTS________________________________
      ---------------------------- Channel - DRP Ports  --------------------------
      gt0_drpaddr_in           => gt0_drpaddr_in,
      gt0_drpclk_in            => gt0_drpclk_in,
      gt0_drpdi_in             => gt0_drpdi_in,
      gt0_drpdo_out            => gt0_drpdo_out,
      gt0_drpen_in             => gt0_drpen_in,
      gt0_drprdy_out           => gt0_drprdy_out,
      gt0_drpwe_in             => gt0_drpwe_in,
      ------------------------------- Loopback Ports -----------------------------
      gt0_loopback_in          => gt0_loopback_in,
      --------------------- RX Initialization and Reset Ports --------------------
      gt0_eyescanreset_in      => gt0_eyescanreset_in,
      -------------------------- RX Margin Analysis Ports ------------------------
      gt0_eyescandataerror_out => gt0_eyescandataerror_out,
      gt0_eyescantrigger_in    => gt0_eyescantrigger_in,
      ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
      gt0_dmonitorout_out      => gt0_dmonitorout_out,
      ------------- Receive Ports - RX Initialization and Reset Ports ------------
      gt0_gtrxreset_in         => gt0_gtrxreset_in,
      gt0_rxlpmreset_in        => gt0_rxlpmreset_in,
      --------------------- TX Initialization and Reset Ports --------------------
      gt0_gttxreset_in         => gt0_gttxreset_in,
      gt0_txuserrdy_in         => gt0_txuserrdy_in,
      ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
      gt0_txdata_in            => gt0_txdata_in,
      gt0_txusrclk_in          => gt0_txusrclk_in,
      gt0_txusrclk2_in         => gt0_txusrclk2_in,
      ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
      gt0_txcharisk_in         => gt0_txcharisk_in,
      --------------- Transmit Ports - TX Configurable Driver Ports --------------
      gt0_gtptxn_out           => gt0_gtptxn_out,
      gt0_gtptxp_out           => gt0_gtptxp_out,
      gt0_txdiffctrl_in        => gt0_txdiffctrl_in,
      ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
      gt0_txoutclk_out         => gt0_txoutclk_out,
      gt0_txoutclkfabric_out   => gt0_txoutclkfabric_out,
      gt0_txoutclkpcs_out      => gt0_txoutclkpcs_out,
      ------------- Transmit Ports - TX Initialization and Reset Ports -----------
      gt0_txpcsreset_in        => gt0_txpcsreset_in,
      gt0_txpmareset_in        => gt0_txpmareset_in,
      gt0_txresetdone_out      => gt0_txresetdone_out,

      --GT1  (X0Y1)
      --____________________________CHANNEL PORTS________________________________
      ---------------------------- Channel - DRP Ports  --------------------------
      gt1_drpaddr_in           => gt1_drpaddr_in,
      gt1_drpclk_in            => gt1_drpclk_in,
      gt1_drpdi_in             => gt1_drpdi_in,
      gt1_drpdo_out            => gt1_drpdo_out,
      gt1_drpen_in             => gt1_drpen_in,
      gt1_drprdy_out           => gt1_drprdy_out,
      gt1_drpwe_in             => gt1_drpwe_in,
      ------------------------------- Loopback Ports -----------------------------
      gt1_loopback_in          => gt1_loopback_in,
      --------------------- RX Initialization and Reset Ports --------------------
      gt1_eyescanreset_in      => gt1_eyescanreset_in,
      -------------------------- RX Margin Analysis Ports ------------------------
      gt1_eyescandataerror_out => gt1_eyescandataerror_out,
      gt1_eyescantrigger_in    => gt1_eyescantrigger_in,
      ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
      gt1_dmonitorout_out      => gt1_dmonitorout_out,
      ------------- Receive Ports - RX Initialization and Reset Ports ------------
      gt1_gtrxreset_in         => gt1_gtrxreset_in,
      gt1_rxlpmreset_in        => gt1_rxlpmreset_in,
      --------------------- TX Initialization and Reset Ports --------------------
      gt1_gttxreset_in         => gt1_gttxreset_in,
      gt1_txuserrdy_in         => gt1_txuserrdy_in,
      ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
      gt1_txdata_in            => gt1_txdata_in,
      gt1_txusrclk_in          => gt1_txusrclk_in,
      gt1_txusrclk2_in         => gt1_txusrclk2_in,
      ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
      gt1_txcharisk_in         => gt1_txcharisk_in,
      --------------- Transmit Ports - TX Configurable Driver Ports --------------
      gt1_gtptxn_out           => gt1_gtptxn_out,
      gt1_gtptxp_out           => gt1_gtptxp_out,
      gt1_txdiffctrl_in        => gt1_txdiffctrl_in,
      ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
      gt1_txoutclk_out         => gt1_txoutclk_out,
      gt1_txoutclkfabric_out   => gt1_txoutclkfabric_out,
      gt1_txoutclkpcs_out      => gt1_txoutclkpcs_out,
      ------------- Transmit Ports - TX Initialization and Reset Ports -----------
      gt1_txpcsreset_in        => gt1_txpcsreset_in,
      gt1_txpmareset_in        => gt1_txpmareset_in,
      gt1_txresetdone_out      => gt1_txresetdone_out,

      --GT2  (X0Y2)
      --____________________________CHANNEL PORTS________________________________
      ---------------------------- Channel - DRP Ports  --------------------------
      gt2_drpaddr_in           => gt2_drpaddr_in,
      gt2_drpclk_in            => gt2_drpclk_in,
      gt2_drpdi_in             => gt2_drpdi_in,
      gt2_drpdo_out            => gt2_drpdo_out,
      gt2_drpen_in             => gt2_drpen_in,
      gt2_drprdy_out           => gt2_drprdy_out,
      gt2_drpwe_in             => gt2_drpwe_in,
      ------------------------------- Loopback Ports -----------------------------
      gt2_loopback_in          => gt2_loopback_in,
      --------------------- RX Initialization and Reset Ports --------------------
      gt2_eyescanreset_in      => gt2_eyescanreset_in,
      -------------------------- RX Margin Analysis Ports ------------------------
      gt2_eyescandataerror_out => gt2_eyescandataerror_out,
      gt2_eyescantrigger_in    => gt2_eyescantrigger_in,
      ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
      gt2_dmonitorout_out      => gt2_dmonitorout_out,
      ------------- Receive Ports - RX Initialization and Reset Ports ------------
      gt2_gtrxreset_in         => gt2_gtrxreset_in,
      gt2_rxlpmreset_in        => gt2_rxlpmreset_in,
      --------------------- TX Initialization and Reset Ports --------------------
      gt2_gttxreset_in         => gt2_gttxreset_in,
      gt2_txuserrdy_in         => gt2_txuserrdy_in,
      ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
      gt2_txdata_in            => gt2_txdata_in,
      gt2_txusrclk_in          => gt2_txusrclk_in,
      gt2_txusrclk2_in         => gt2_txusrclk2_in,
      ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
      gt2_txcharisk_in         => gt2_txcharisk_in,
      --------------- Transmit Ports - TX Configurable Driver Ports --------------
      gt2_gtptxn_out           => gt2_gtptxn_out,
      gt2_gtptxp_out           => gt2_gtptxp_out,
      gt2_txdiffctrl_in        => gt2_txdiffctrl_in,
      ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
      gt2_txoutclk_out         => gt2_txoutclk_out,
      gt2_txoutclkfabric_out   => gt2_txoutclkfabric_out,
      gt2_txoutclkpcs_out      => gt2_txoutclkpcs_out,
      ------------- Transmit Ports - TX Initialization and Reset Ports -----------
      gt2_txpcsreset_in        => gt2_txpcsreset_in,
      gt2_txpmareset_in        => gt2_txpmareset_in,
      gt2_txresetdone_out      => gt2_txresetdone_out,

      --GT3  (X0Y3)
      --____________________________CHANNEL PORTS________________________________
      ---------------------------- Channel - DRP Ports  --------------------------
      gt3_drpaddr_in           => gt3_drpaddr_in,
      gt3_drpclk_in            => gt3_drpclk_in,
      gt3_drpdi_in             => gt3_drpdi_in,
      gt3_drpdo_out            => gt3_drpdo_out,
      gt3_drpen_in             => gt3_drpen_in,
      gt3_drprdy_out           => gt3_drprdy_out,
      gt3_drpwe_in             => gt3_drpwe_in,
      ------------------------------- Loopback Ports -----------------------------
      gt3_loopback_in          => gt3_loopback_in,
      --------------------- RX Initialization and Reset Ports --------------------
      gt3_eyescanreset_in      => gt3_eyescanreset_in,
      -------------------------- RX Margin Analysis Ports ------------------------
      gt3_eyescandataerror_out => gt3_eyescandataerror_out,
      gt3_eyescantrigger_in    => gt3_eyescantrigger_in,
      ------------ Receive Ports - RX Decision Feedback Equalizer(DFE) -----------
      gt3_dmonitorout_out      => gt3_dmonitorout_out,
      ------------- Receive Ports - RX Initialization and Reset Ports ------------
      gt3_gtrxreset_in         => gt3_gtrxreset_in,
      gt3_rxlpmreset_in        => gt3_rxlpmreset_in,
      --------------------- TX Initialization and Reset Ports --------------------
      gt3_gttxreset_in         => gt3_gttxreset_in,
      gt3_txuserrdy_in         => gt3_txuserrdy_in,
      ------------------ Transmit Ports - FPGA TX Interface Ports ----------------
      gt3_txdata_in            => gt3_txdata_in,
      gt3_txusrclk_in          => gt3_txusrclk_in,
      gt3_txusrclk2_in         => gt3_txusrclk2_in,
      ------------------ Transmit Ports - TX 8B/10B Encoder Ports ----------------
      gt3_txcharisk_in         => gt3_txcharisk_in,
      --------------- Transmit Ports - TX Configurable Driver Ports --------------
      gt3_gtptxn_out           => gt3_gtptxn_out,
      gt3_gtptxp_out           => gt3_gtptxp_out,
      gt3_txdiffctrl_in        => gt3_txdiffctrl_in,
      ----------- Transmit Ports - TX Fabric Clock Output Control Ports ----------
      gt3_txoutclk_out         => gt3_txoutclk_out,
      gt3_txoutclkfabric_out   => gt3_txoutclkfabric_out,
      gt3_txoutclkpcs_out      => gt3_txoutclkpcs_out,
      ------------- Transmit Ports - TX Initialization and Reset Ports -----------
      gt3_txpcsreset_in        => gt3_txpcsreset_in,
      gt3_txpmareset_in        => gt3_txpmareset_in,
      gt3_txresetdone_out      => gt3_txresetdone_out,


      --____________________________COMMON PORTS________________________________
      GT0_PLL0OUTCLK_IN     => GT0_PLL0OUTCLK_IN,
      GT0_PLL0OUTREFCLK_IN  => GT0_PLL0OUTREFCLK_IN,
      GT0_PLL0RESET_OUT     => GT0_PLL0RESET_OUT,
      GT0_PLL0LOCK_IN       => GT0_PLL0LOCK_IN,
      GT0_PLL0REFCLKLOST_IN => GT0_PLL0REFCLKLOST_IN,
      GT0_PLL1OUTCLK_IN     => GT0_PLL1OUTCLK_IN,
      GT0_PLL1OUTREFCLK_IN  => GT0_PLL1OUTREFCLK_IN

      );

end RTL;
